= dftd4-fit(1)
:doctype: manpage

== Name
dftd4-fit - Damping parameter optimization for DFT-D4

== Synopsis
*dftd4-fit* [-h|--help] [--version] [--license] [--citation]
            [-v|--verbose] [-s|--silent]
            [-C|--directory <directory>] [--algorithm <algorithm>]
            [--ftol <tol>] [--xtol <tol>] [--param <s8> <a1> <a2>]
            <input>

== Description

Optimization driver for damping parameters in DFT-D4 using NLOpt.
As input a data set is required containing the missing dispersion energies
for the respective functional in Hartree.

The input file is a simple text file containing the following columns:

[source,csv]
----
S22x5/01-0.9, S22x5/01-A, S22x5/01-B, 1.0007611865e-03
S22x5/01-1.0, S22x5/01-A, S22x5/01-B, 1.5228237266e-03
S22x5/01-1.2, S22x5/01-A, S22x5/01-B, 1.6586059147e-03
S22x5/01-1.5, S22x5/01-A, S22x5/01-B, 1.2297590834e-03
S22x5/01-2.0, S22x5/01-A, S22x5/01-B, 6.2420992500e-04
...
----

The geometries for the individual records will be read from `mol.xyz` files in
the respective directories, like present in https://github.com/dftd4/dftd4-fitset.


== Options

*-v, --verbose*::
  Show more, can be used multiple times

*-s, --silent*::
  Show less, use twice to supress all output

*--algorithm* _str_::
  Name of the algorithm used for optimization.
  Available algorithms can be found at https://nlopt.rtfd.io
  The default algorithm is 'LN_NEWUOA_BOUND'.

*-C, --directory* _dir_::
  Directory containing data set

*--ftol* _real_::
  Tolerance for convergence of error on data set

*--xtol* _real_::
  Tolerance for convergence of parameters

*--param* _s8_ _a1_ _a2_::
  Initial parameters (s8, a1, a2)

*--version*::
  Print program version and exit

*--citation*::
  Print citation information and exit

*--license*::
  Print license header and exit

*-h, --help*::
  Show this help message


Command line arguments can be read from an indirect file / response file by specifying the file with @_name_ in the command line.
Each line in the file is interpreted as command line argument, shell like escape sequences are not available.
The file can contain further @_name_ inputs. If the file cannot be the argument is used literally.
