name = "dftd4-fit"
version = "0.1.0"
license = "LGPL-3.0-or-later"
maintainer = ["@awvwgk"]
author = ["Sebastian Ehlert"]
description = "Generally Applicable Atomic-Charge Dependent London Dispersion Correction"
keywords = ["quantum-chemistry", "dispersion-correction"]
copyright = "Copyright 2021 S. Ehlert"

[dependencies]
mctc-lib.git = "https://github.com/grimme-lab/mctc-lib.git"
dftd4.git = "https://github.com/dftd4/dftd4.git"
nlopt-f.git = "https://github.com/grimme-lab/nlopt-f.git"
minpack.git = "https://github.com/fortran-lang/minpack.git"
