name = "dftd4-fit"

[dependencies]
mctc-lib.git = "https://github.com/grimme-lab/mctc-lib.git"
dftd4.git = "https://github.com/dftd4/dftd4.git"
nlopt-f.git = "https://github.com/grimme-lab/nlopt-f.git"
